# Generated by Django 2.0.1 on 2018-03-15 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistName', models.CharField(max_length=200)),
                ('artistAge', models.IntegerField(default=0)),
                ('artistNationality', models.CharField(max_length=200)),
                ('artistInterest', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FieldofWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=200)),
                ('works', models.CharField(max_length=200)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.Artist')),
            ],
        ),
    ]
