# Generated by Django 2.0.1 on 2018-03-17 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_usertoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertoken',
            name='user',
        ),
    ]
